name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant
    
    - name: Build with Ant
      run: ant clean war
    
    - name: Build Docker image
      run: docker build -t sql-gateway .
      
    - name: Test Docker image
      run: |
        docker run -d -p 8080:8080 --name test-container sql-gateway
        sleep 30
        curl -f http://localhost:8080/ || exit 1
        docker stop test-container